### ISSUE TITLE
Check if bot has valid permissions

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/KMQ_Discord#103]

**Comment by taahamahdi** [comment]
Shouldn't be a problem if we make the bot invite link have the correct permission already. The README and invite link on bot.gg have [this.](https://discordapp.com/oauth2/authorize?client_id=508759831755096074&scope=bot&permissions=3165184)

**Comment by Brainicism** [comment]
Server owner can manually revoke permissions or assign different roles after it's been invited

**Comment by taahamahdi** [comment]
![Screenshot from 2020-04-19 00-40-36](https://user-images.githubusercontent.com/14286913/79679713-6e325c00-81d6-11ea-8654-92a0f572160a.png)

**Comment by Brainicism** [comment]
nvm
