### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/KMQ_Discord#1300]
![image](https://user-images.githubusercontent.com/13823855/165008188-74d3e026-a605-487f-8a9a-ffce6e63afd7.png)
![image](https://user-images.githubusercontent.com/13823855/165008199-6e06d469-efc6-4253-9c01-fbbc99192c77.png)

**Comment by taahamahdi** [comment]
Can't reproduce the Groups and Exclude Conflict.
