### ISSUE TITLE
Prune inactive songs from cache

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/KMQ_Discord#132]

**Comment by taahamahdi** [comment]
What is an inactive song? Do you define these as songs not in the database anymore?

**Comment by Brainicism** [comment]
Song that hasn't been played within a specific timeframe (1 month?)

**Comment by taahamahdi** [comment]
How can we determine how long it's been since it was played? Can we scan the logs to do this?

**Comment by Brainicism** [comment]
`touch` the cached files every time they're played. Run a cron-based script every day to check for files not touched in the last month

**Comment by taahamahdi** [comment]
Thanks for the explanation!
