### ISSUE TITLE
Error message when insufficient permissions

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/KMQ_Discord#134]
[2020-05-11T17:35:08.721] [ERROR] Error joining voice connection. cached = false. song = Lucky Strike:Dreamcatcher:AM7ro_nBCHI err = Error [VOICE_JOIN_CHANNEL]: You do not have permission to join this voice channel.

**Comment by taahamahdi** [comment]
https://discordapi.com/permissions.html#3165184

How is this possible with these permissions? I thought connecting to a VC was included with the invite link? Unless the user modified a voice channel to not allow the bot to join.

**Comment by Brainicism** [comment]
Private channel

**Comment by taahamahdi** [comment]
Just so we remember what we have to do for this issue: We need to direct message the user that attempted to use the bot that there are permission errors.

**Comment by Brainicism** [comment]
It depends on what the missing permission is. In this issue specifically, it's a voice channel that the bot can't access. In other cases, it's a text channel that it can't send messages in.
