### ISSUE TITLE
Investigate memory leaks

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/KMQ_Discord#175]
Memory usage monotonously increases until node process is no longer able to allocate memory

**Comment by Brainicism** [comment]
Memory leak appears to be caused by `StreamDispatcher`'s behavior in discord.js versions >=12.0.0. Reverting to 11.6.4 temporarily 
https://github.com/discordjs/discord.js/issues/4287

**Comment by taahamahdi** [comment]
Marking as wontfix for now until Discord.js gets a fix and we can revert back.

**Comment by Brainicism** [comment]
Migrating to Eris resolved this issue
