### ISSUE TITLE
they got rid of t shirts

### ISSUE THREAD

**Issue by kambojk** [Brainicism/KMQ_Discord#1760]
> We believe that even without t-shirt rewards, the developer community will continue to come together in the same spirit of Hacktoberfest that they’ve always shown.

dude what is the point anymore?

**Comment by Brainicism** [comment]
wait i did my 4 PRs already and theres no tshirt??????

**Comment by taahamahdi** [comment]
![Screenshot 2023-10-24 at 10 48 59 PM](https://github.com/Brainicism/KMQ_Discord/assets/14286913/4068430c-948d-4638-8a13-876ea6ad0e38)
