### ISSUE TITLE
Better messaging for when a game round ends

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/KMQ_Discord#200]
Currently just default to `sendSongMessage` for everything, should make it a bit more detailed

**Comment by taahamahdi** [comment]
Can you clarify the title of the issue? Thanks :]

**Comment by Brainicism** [comment]
`sendSongMessage` was originally written to be used when a song was correctly guessed to provide additional context. However, we've been using it in other places as well. It's also find in `,end` and `,skip` because we provide additional messaging to indicate what happened as well. However, in `,stop`, ` gameSession.dispatcher.once("end"),` and when a song is guessed, there is no distinction
