### ISSUE TITLE
,skip gets wrong count of participants

### ISSUE THREAD

**Issue by taahamahdi** [Brainicism/KMQ_Discord#416]
**Describe the bug**
Once reproduced in a game session, it continues to happen. In the only case it was reproduced, there were 3 players, yet KMQ was reporting 1 participant, and was allowing a ,skip with only one call instead of the required 2.

**Expected behavior**
Always get correct number of participants needed to ,skip

**Additional context**
Possibly occurring because of user cache sweeping

getSkipsRequired is `Math.floor(getNumParticipants(message) * 0.5) + 1;`
and getNumParticipants is `return (getVoiceChannel(message).voiceMembers.filter((x) => !x.bot)).length;`

**Comment by Brainicism** [comment]
Presumably resolved
