### ISSUE TITLE
Count skip majority based on voice channel participants

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/KMQ_Discord#60]

**Comment by Brainicism** [comment]
@taahamahdi Still requires changes to use the number of people in a voice call in the skip majority calculation

**Comment by taahamahdi** [comment]
Do we define a participant as (1) someone in the bot's voice channel, or (2) someone who is in the bot's voice channel and has interacted with it somehow (guessed or sent a command to a bot in the current round)? The current code implements 2.

**Comment by Brainicism** [comment]
1). Someone who is in the bot's channel for simplicity

**Comment by taahamahdi** [comment]
Is this what you had in mind? I can make a PR if it is.

**Comment by Brainicism** [comment]
Looks good to me assuming you've tested it

**Comment by taahamahdi** [comment]
I have, I'll make a PR.
