### ISSUE TITLE
Store average guess time somehow in song guess count

### ISSUE THREAD

**Issue by taahamahdi** [Brainicism/KMQ_Discord#645]
It might be a better measure of difficulty than `correct guesses / total rounds` alone

**Comment by Brainicism** [comment]
Average guess time is a noisy metric: some people might afk and leave the song playing until the end, some people might wait for the song to end just to listen to it. `correct guesses/total rounds` provides a binary yes/no

**Comment by taahamahdi** [comment]
Good point, I didn't consider all use cases of the bot for this one. I'm gonna close it.
