### ISSUE TITLE
Incorrect winner in teams mode

### ISSUE THREAD

**Issue by taahamahdi** [Brainicism/KMQ_Discord#688]
Potentially caused by an off-by-one error. `getWinnerMessage()` needs to be investigated

![wrong-winner](https://user-images.githubusercontent.com/14286913/115107337-3c162000-9f38-11eb-850f-708a58443391.png)

**Comment by ProBeta1** [comment]
Quite interesting bug . The functions involved look fine , its even difficult to reproduce .

**Comment by taahamahdi** [comment]
First goal was set to 100. Then it hit it but didn't end the game. Then, goal was set to 100 again and promptly reset. Team nct reached 101 points and then the goal was set to 100. Then, once skz reached 100, it triggered the goal and ended the game (as a winner).

Much went wrong this game.

[The start of events](https://discord.com/channels/679165980995223582/710578841394872332/832878679310204948) for reference.

**Comment by Brainicism** [comment]
It looks more like the game ended because everyone left
