### ISSUE TITLE
Korean only song names have empty string as song names

### ISSUE THREAD

**Issue by DannyKong12** [Brainicism/KMQ_Discord#72]
utils.js/cleanSongNames removes non-ascii characters, including korean characters

**Comment by taahamahdi** [comment]
@DannyKong12 suggests we convert all Korean characters in song names to their romanized version on database creation.

**Comment by Brainicism** [comment]
Good suggestion but I'm not sure if hangul->romanization is always a 1:1 mapping. Could you look into it

**Comment by DannyKong12** [comment]
it would be good to have a small list of possible answers instead of one correct answer, there are a few variants of romanization too but some are more popular

**Comment by taahamahdi** [comment]
https://github.com/Tyriar/hangul-romanization
