### ISSUE TITLE
Give user more formal warning that config.json does not exist

### ISSUE THREAD

**Issue by taahamahdi** [Brainicism/KMQ_Discord#74]
Currently fails on `npm run seed`, leaving impression something went wrong with DB creation.

Would it be reasonable for us to use the template file as their config file if they haven't created their own `config.json`?

**Comment by Brainicism** [comment]
No, template file doesn't contain any useful configuration data. Should give them a warning if config doesn't exist

**Comment by taahamahdi** [comment]
I agree, what step should we generate the warning?

**Comment by taahamahdi** [comment]
Do we need some sort of intermediary or should we just add in the message directly to `seed_db.js`?

**Comment by Brainicism** [comment]
The very beginning, inside of line 52 of kmq.js

**Comment by taahamahdi** [comment]
Won't that only get executed when the user runs `npm start` though? If they're failing to get past `npm run seed`, I don't see how anything in kmq.js will get executed

**Comment by Brainicism** [comment]
I forgot that the seed also uses config,  should also perform the check in the main function in seed_db too

**Comment by Brainicism** [comment]
Typescript will no longer let this compile if the file is missing.
